# Generated by Django 5.0.6 on 2024-07-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
